Use format string
gcc complain about a missing format argument.

rem.c:502:18: error: format not a string literal and no format arguments [-Werror=format-security]
    fprintf(mbox, line);
                  ^~~~

Rework to use a format argument.

Signed-off-by: Benedikt Spranger <bene@eurovibes.org>